version: 0.1
component: build
timeoutInSeconds: 6000
runAs: root
shell: bash
env:
  variables:
    "testEnv" : "defaultTestVariable"
    "primaryCodeRepoCommitHash" : "000"
  exportedVariables:
    - VERS
    - param1
    - primaryCodeRepoCommitHash
steps:
  - type: Command
    name: "pre-build"
    command: |
      echo "build is starting"
      export primaryCodeRepoCommitHash=${OCI_PRIMARY_SOURCE_COMMIT_HASH}
  - type: Command
    name: "build"
    command: |
      ./gradlew build
outputArtifacts:
- name: gradleBuildScanQuickstart
  type: BINARY
  location: build/libs/gradle-build-scan-quickstart.jar
