version: 0.1
component: build
timeoutInSeconds: 6000
runAs: root
shell: bash
env:
  variables:
    "testEnv" : "defaultTestVariable"
inputArtifacts:
  - name: artifact-name
    type: URL
    url: https://objectstorage.us-ashburn-1.oraclecloud.com/p/JhvYThishjVpSH6cDBzsPIiSs8TleWraBlcLsEPqk3F0mOafg6ebmjM51PMxwRNB/n/idllbnfszw6v/b/UNIT_TESTING_FILES-DO_NOT_DELETE/o/integ-testing-DO-NOT-DELETE-pom.xml
    location: ${OCI_PRIMARY_SOURCE_DIR}/pom.xml

steps:
  - type: Command
    name: "Print input artifact contents"
    timeoutInSeconds: 500
    command: |
      head -n 25 ${OCI_PRIMARY_SOURCE_DIR}/pom.xml
