version: 0.1
component: build
timeoutInSeconds: 6000
runAs: root
shell: bash
env:
  variables:
    "testEnv" : "defaultTestVariable"
  exportedVariables:
    - VERS
    - param1

steps:
  - type: Command
    name: "pre-build"
    timeoutInSeconds: 5
    command: |
      sleep 25
    onFailure:
      - type: Command
        command: |
          echo "Entered on failure block"
          
