version: 0.1
component: build
timeoutInSeconds: 6000
runAs: root
shell: bash
env:
  variables:
    "testEnv" : "defaultTestVariable"
  exportedVariables:
    - VERS
    - param1

steps:
  - type: Command
    name: "pre-build"
    command: |
      echo "build is starting"
  - type: Command
    name: "build"
    command: |
      ./gradlew build
outputArtifacts:
- name: gradleBuildScanQuickstart
  type: BINARY
  location: build/libs/gradle-build-scan-quickstart.jar
