version: 0.1
component: build
timeoutInSeconds: 6000
runAs: root
shell: bash
env:
  variables:
    "testEnv" : "defaultTestVariable"
  exportedVariables:
    - VERS
    - param1

steps:
  - type: Command
    name: "buildSource1"
    command: |
      cd ${OCI_WORKSPACE_DIR}/TestBuildSource2
      mvn clean install
      java -jar target/my-app-1.0-SNAPSHOT.jar
  - type: Command
    name: "buildSource2"
    command: |
      cd ${OCI_WORKSPACE_DIR}/TestBuildSource1
      ./gradlew build
  - type: Command
    name: "buildSource3"
    command: |
      cd ${OCI_WORKSPACE_DIR}/TestBuildSource3
      mvn clean install
      java -jar target/my-app-1.0-SNAPSHOT.jar
      
outputArtifacts:
- name: maven
  type: BINARY
  location: ${OCI_WORKSPACE_DIR}/TestBuildSource2/target/my-app-1.0-SNAPSHOT.jar
- name: gradle
  type: BINARY
  location: ${OCI_WORKSPACE_DIR}/TestBuildSource1/build/libs/gradle-build-scan-quickstart.jar
- name: maven2
  type: BINARY
  location: ${OCI_WORKSPACE_DIR}/TestBuildSource3/target/my-app-1.0-SNAPSHOT.jar
